from pathlib import Path
import json,html
R=Path(__file__).parent
E=html.escape
sites=[]
def site(slug,name,kind,theme,image,title,lead,tag,items,extra=None):
 d=dict(slug=slug,name=name,kind=kind,theme=theme,image=image,title=title,lead=lead,tag=tag,items=items);d.update(extra or {});sites.append(d);return d
# Five independent guest experiences.
site('guest-mare','Maré','GuestHub · Resort mediterráneo','coast','sea','Tu tiempo.<br>Tu Mediterráneo.','Todo lo que necesitas para disfrutar de tu estancia, a un solo toque. Baja el ritmo. Nosotros te guiamos.','COSTA / CALMA / CONTIGO',[
['Llegada sin prisas','Desde las 15:00','Recepción de 08:00 a 23:00. Si llegas más tarde, prepara una solicitud al equipo.','Llegada'],['Desayuno frente al mar','07:30 — 10:30','Buffet en la terraza de la planta baja. Opciones vegetales disponibles bajo consulta.','Gastronomía'],['Piscina & solárium','09:00 — 20:00','Toallas junto al acceso. Los menores deben estar acompañados.','Bienestar'],['Tu última mañana','Salida hasta las 11:00','Deja la llave en recepción. Puedes solicitar guardar el equipaje.','Llegada']],{'guest':True,'place':'Mediterráneo','wifi':'MARE_GUEST_DEMO','password':'mare-demo-2026','experience':['Paseo por la costa','Mercado de productores','Atardecer en kayak'],'colors':['#f5efe4','#172c35','#136775'],'layout':'immersive','serviceOptions':['Toallas adicionales','Consulta de desayuno','Guardar equipaje','Llegada tardía'],'enTitle':'Your time.<br>Your Mediterranean.','enLead':'Everything you need for your stay, one tap away. Slow down. We will guide you.'})
site('guest-distrito','Distrito 08','GuestHub · Apartamentos urbanos','city','city','La ciudad es tuya.','Tu apartamento, tus planes y todos los detalles de tu estancia en un panel. Sal y descubre Barcelona a tu manera.','YOUR CITY / YOUR STAY',[
['Acceso al apartamento','Check-in desde las 16:00','En esta demo el acceso se explica con una guía. Los códigos reales se compartirían por un canal privado.','Llegada'],['Café & cowork','08:00 — 19:00','Elige una mesa en el lounge para trabajar o planear tu día.','Servicios'],['Muévete en metro','Conecta con el barrio','Consulta las recomendaciones de transporte de tu anfitrión antes de salir.','Ciudad'],['Check-out sencillo','Hasta las 11:00','Revisa que no dejas nada, cierra ventanas y deposita las llaves donde indica la guía.','Llegada']],{'guest':True,'place':'Barcelona','wifi':'DISTRITO_DEMO','password':'city-demo-only','experience':['Ruta de arquitectura','Café de especialidad','Paseo por el barrio'],'colors':['#10151f','#f5f7fc','#75e1e6'],'layout':'dashboard','serviceOptions':['Consulta de acceso','Mantenimiento','Guardar equipaje','Salida tardía'],'enTitle':'The city is yours.','enLead':'Your apartment, your plans and all the details of your stay in one dashboard.'})
site('guest-bosque','Casa Bosque','GuestHub · Turismo rural','forest','forest','Respira.<br>Ya estás en casa.','Una guía tranquila para una estancia entre árboles. Descubre la casa, el entorno y pequeños planes que merecen tiempo.','MENOS RUIDO. MÁS NATURALEZA.',[
['La bienvenida','Desde las 15:00','Tu anfitrión te recibe en el patio. Prepara una consulta si necesitas llegar fuera del horario.','Llegada'],['La cocina de la casa','Comparte la mesa','Encuentra utensilios en los cajones señalizados. Separa los residuos en las cubetas del patio.','La casa'],['Chimenea & descanso','Disfrutar con cuidado','Consulta al anfitrión antes de encenderla y sigue las instrucciones de la casa.','La casa'],['Rutas cerca de casa','Elige tu ritmo','Pide información sobre dificultad, previsión y equipamiento antes de iniciar una ruta.','Entorno']],{'guest':True,'place':'Entorno rural','wifi':'BOSQUE_DEMO','password':'forest-demo-only','experience':['Sendero entre árboles','Taller de pan artesano','Picnic de temporada'],'colors':['#f1f0e4','#253d2b','#567052'],'layout':'editorial','serviceOptions':['Llegada fuera de horario','Información de rutas','Cesta de desayuno','Leña para la chimenea'],'enTitle':'Breathe.<br>You are home.','enLead':'A calm guide to your stay among trees. Discover the house and the world outside.'})
site('guest-maison','Maison Alba','GuestHub · Hotel boutique','boutique','boutique','El arte de<br>quedarte.','Detalles cuidados, momentos propios. Tu concierge digital para descubrir cada rincón de Maison Alba.','A STAY TO REMEMBER',[
['Un recibimiento personal','Desde las 15:00','En el salón de entrada encontrarás a nuestro equipo. Consulta cualquier necesidad antes de llegar.','Llegada'],['Desayuno a tu ritmo','08:00 — 11:00','Selecciona tu preferencia en solicitudes. La disponibilidad se confirma con recepción.','Gastronomía'],['Spa & bienestar','Bajo solicitud','Consulta los tratamientos y horarios del espacio de bienestar.','Bienestar'],['Biblioteca & salón','Tu pausa favorita','Lee, disfruta de un café o descubre nuestra selección de diseño.','Experiencias']],{'guest':True,'place':'Hotel boutique','wifi':'MAISON_DEMO','password':'alba-demo-only','experience':['Arquitectura & diseño','Degustación de temporada','Paseo cultural privado'],'colors':['#f5edf3','#342238','#8a5e74'],'layout':'arch','serviceOptions':['Preferencia de desayuno','Consulta de spa','Experiencia cultural','Servicio de habitación'],'enTitle':'The art of<br>staying.','enLead':'Thoughtful details, your own moments. A digital concierge for every corner of Maison Alba.'})
site('guest-nomad','Nomad Social','GuestHub · Hostel & comunidad','hostel','hostel','CHECK IN.<br>GO OUT.<br>CONNECT.','La guía del hostel para viajeros que vienen a conocer gente, explorar el barrio y vivir algo nuevo.','SLEEP / EXPLORE / REPEAT',[
['Tu primera parada','Check-in 15:00','Recoge tu llave en el mostrador. Pregunta por las actividades de esta semana.','Llegada'],['Cocina compartida','07:00 — 23:00','Etiqueta tu comida y limpia después de usar el espacio. Compartir también es cuidar.','Hostel'],['Zona chill','Conecta sin ruido','Juegos y conversación hasta las 23:00. Después, modo descanso.','Hostel'],['Tu mochila, a salvo','Consulta recepción','Solicita información sobre consignas. No compartas códigos personales.','Servicios']],{'guest':True,'place':'Hostel urbano','wifi':'NOMAD_DEMO','password':'nomad-demo-only','experience':['Paseo en grupo','Cena compartida','Ruta de arte urbano'],'colors':['#ff653c','#171717','#f5f14b'],'layout':'poster','serviceOptions':['Consigna de equipaje','Actividad de grupo','Toalla adicional','Consulta de habitación'],'enTitle':'CHECK IN.<br>GO OUT.<br>CONNECT.','enLead':'Your hostel guide for meeting people, exploring the neighbourhood and trying something new.'})
# Ten sector-specific websites, with purpose-built commercial interactions.
site('restaurante-brasa','Brasa & Sal','Restaurante','restaurant','restaurant','El fuego.<br>La mesa.<br>El momento.','Cocina de temporada, brasas encendidas y sobremesas que no miran el reloj. Descubre una carta que cambia con el mercado.','COCINA ABIERTA / MESA COMPARTIDA',[
['Burrata de temporada','Entrantes',14,'Tomate, albahaca y aceite de oliva. Contiene leche.'],['Verduras a la brasa','Entrantes',12,'Selección de temporada, romesco. Contiene frutos secos.'],['Arroz del día','Principales',22,'Pregunta por los ingredientes del día. Precio por persona.'],['Pescado de lonja','Principales',26,'Guarnición de verduras. Contiene pescado.'],['Tarta de queso','Postres',8,'Cremosa, con frutos rojos. Contiene leche, huevo y gluten.'],['Chocolate & sal','Postres',8,'Chocolate negro y aceite. Consulta alérgenos.']],{'colors':['#191914','#f1e7d1','#e88542'],'layout':'centered','feature':'menu','sectionTitle':'Una carta con carácter.','cta':'Preparar reserva','services':['Mesa para dos','Celebración en grupo','Consulta de carta'],'story':'Producto de temporada. Cocción honesta. Un comedor donde cada plato invita a quedarse. Esta propuesta reúne carta, reserva y experiencia en una sola web.','storyImage':'food'})
site('clinica-clara','Clara Dental','Clínica dental','dental','dental','Una sonrisa.<br>Más tranquilidad.','Una propuesta de clínica cercana, donde las explicaciones son claras y cada visita empieza escuchándote.','CLARIDAD EN CADA VISITA',[
['Primera visita','Valoración',0,'Conoce al equipo y plantea tus dudas. Las condiciones se confirman con la clínica.'],['Higiene dental','Prevención',55,'Servicio de ejemplo. La idoneidad se valora de forma individual.'],['Ortodoncia','Tratamientos',0,'Información sobre alternativas, proceso y seguimiento.'],['Estética dental','Tratamientos',0,'Consulta opciones con un profesional tras valoración.'],['Odontología infantil','Familias',0,'Una visita adaptada al ritmo de cada peque.'],['Seguimiento','Prevención',0,'Agenda una revisión según las indicaciones de tu profesional.']],{'colors':['#eff8fa','#143947','#2b7484'],'layout':'bento','feature':'treatments','sectionTitle':'Preguntar es el primer paso.','cta':'Preparar cita','services':['Primera visita','Higiene dental','Ortodoncia','Estética dental','Odontología infantil'],'story':'Un espacio pensado para entender tu tratamiento. Información sencilla sobre el proceso, tiempo para tus preguntas y un equipo presentado con transparencia.','storyImage':'workspace'})
site('barberia-ritual','Ritual Studio','Barbería','barber','barber','BUEN CORTE.<br>BUENA ACTITUD.','Corte, barba y una hora para ti. Un estudio de barbería con oficio, identidad y agenda sin complicaciones.','CUTS / SHAVES / CULTURE',[
['Corte clásico','Corte',24,'40 min · Tijera y acabado.'],['Skin fade','Corte',27,'45 min · Degradado y styling.'],['Barba perfilada','Barba',18,'25 min · Perfilado y cuidado.'],['Corte + barba','Rituales',39,'60 min · El ritual completo.'],['Afeitado tradicional','Barba',22,'30 min · Toalla caliente y acabado.'],['Ritual premium','Rituales',49,'75 min · Corte, barba y cuidado.']],{'colors':['#eee9df','#171717','#c5572d'],'layout':'magazine','feature':'services','sectionTitle':'Encuentra tu ritual.','cta':'Elegir cita','services':['Corte clásico','Skin fade','Barba perfilada','Corte + barba','Ritual premium'],'story':'Una silla. Una conversación. Un corte que encaja contigo. Del estilo clásico a los degradados, el sitio permite explorar servicios y preparar una cita con preferencias.','storyImage':'barber','team':['Alex · Clásicos & tijera','Dani · Fades & textura','Sam · Barba & afeitado']})
site('gimnasio-pulse','PULSE Club','Gimnasio & entrenamiento','gym','gym','MOVE.<br>YOUR.<br>LIMITS.','Fuerza, comunidad y sesiones que se adaptan a tu semana. Encuentra tu clase y construye una rutina a tu ritmo.','ENERGÍA QUE SE CONTAGIA',[
['Strength Lab','Lunes',0,'07:00 · 50 min · Fuerza'],['Mobility Flow','Lunes',0,'18:00 · 45 min · Movilidad'],['Power Circuit','Miércoles',0,'19:00 · 45 min · Circuito'],['Strength Lab','Miércoles',0,'08:00 · 50 min · Fuerza'],['Weekend Reset','Sábado',0,'10:00 · 45 min · Movilidad'],['Team Workout','Sábado',0,'11:00 · 50 min · Equipo']],{'colors':['#101210','#f6f7f1','#cafc3a'],'layout':'kinetic','feature':'classes','sectionTitle':'Tu semana en movimiento.','cta':'Probar una sesión','services':['Clase de prueba','Visita al club','Entrenamiento personal','Información de planes'],'story':'El entrenamiento empieza con un plan que puedas mantener. Explora clases, compara modalidades y prepara una visita para conocer el espacio.','storyImage':'gym'})
site('reformas-forma','FORMA Estudio','Reformas & interiorismo','interior','interior','Espacios para<br>vivir mejor.','Reformas con una idea clara: transformar tu casa con criterio, materiales elegidos y un proceso que puedas entender.','DISEÑO / OBRA / DETALLE',[
['Cocina abierta','Vivienda',0,'Luz natural y una zona de encuentro para toda la casa.'],['Baño sereno','Detalle',0,'Materiales cálidos y soluciones prácticas.'],['Apartamento flexible','Vivienda',0,'Una distribución que acompaña distintas formas de vivir.'],['Espacio de trabajo','Comercial',0,'Orden, acústica y una identidad propia.']],{'colors':['#f2ede6','#39312c','#b86140'],'layout':'editorial','feature':'estimate','sectionTitle':'Una primera idea de tu proyecto.','cta':'Preparar proyecto','services':['Reforma integral','Cocina','Baño','Interiorismo'],'story':'Medir, dibujar, elegir y acompañar. La propuesta explica las fases de una reforma y permite preparar un primer briefing sin prometer un precio cerrado.','storyImage':'home'})
site('inmobiliaria-habita','Habita Studio','Inmobiliaria','home','home','Tu próxima<br>forma de vivir.','Una selección de viviendas para personas, no para números de referencia. Explora, compara y guarda lo que encaja contigo.','HOMES WITH A POINT OF VIEW',[
['Luz en el Eixample','Venta',425000,'82 m² · 2 habitaciones · Barcelona'],['Terraza en el barrio','Alquiler',1350,'65 m² · 2 habitaciones · Barcelona'],['Casa con jardín','Venta',595000,'140 m² · 3 habitaciones · Baix Llobregat'],['Estudio conectado','Alquiler',950,'42 m² · 1 habitación · Barcelona']],{'colors':['#f0f2f7','#17325e','#295bc8'],'layout':'property','feature':'properties','sectionTitle':'Encuentra tu lugar.','cta':'Preparar visita','services':['Visitar una vivienda','Vender mi inmueble','Alquilar mi inmueble','Asesoramiento'],'story':'La información antes que la presión. Fichas claras, favoritos que se guardan en tu dispositivo y un camino sencillo para preparar una visita.','storyImage':'interior'})
site('estetica-luma','Luma Atelier','Estética & bienestar','beauty','beauty','Vuelve<br>a ti.','Un espacio para parar, cuidar y dedicarte tiempo. Rituales de bienestar con una experiencia tan cuidada como el espacio.','PAUSA / CUIDADO / EQUILIBRIO',[
['Ritual facial','Facial',65,'60 min · Cuidado cosmético adaptado tras consulta.'],['Masaje relajante','Corporal',55,'50 min · Una pausa para bajar el ritmo.'],['Manicura esencial','Manos',28,'40 min · Preparación y acabado.'],['Ritual manos & pies','Manos',48,'70 min · Cuidado y acabado completo.'],['Experiencia Luma','Corporal',95,'90 min · Combinación de rituales de ejemplo.']],{'colors':['#f7eff0','#523f48','#9e6377'],'layout':'arch','feature':'services','sectionTitle':'Elige tu momento.','cta':'Preparar cita','services':['Ritual facial','Masaje relajante','Manicura esencial','Experiencia Luma'],'story':'Texturas suaves, luz tranquila y tiempo para escucharte. Una web que presenta el ritual, explica lo que incluye y permite preparar tu preferencia de cita.','storyImage':'beauty'})
site('veterinaria-nido','Nido Vet','Veterinaria','vet','vet','Su bienestar.<br>Tu tranquilidad.','Un espacio de atención veterinaria pensado para acompañar a las familias y explicar cada paso con cercanía.','CERCA DE QUIEN MÁS QUIERES',[
['Consulta general','Perros',0,'Revisión por un profesional y orientación personalizada.'],['Consulta felina','Gatos',0,'Atención adaptada a las necesidades de los gatos.'],['Prevención','Perros',0,'Consulta programas de seguimiento con el equipo.'],['Cuidado senior','Gatos',0,'Valoración y acompañamiento en cada etapa.'],['Primera visita','Otros',0,'Pregunta por las especies y servicios disponibles.']],{'colors':['#f5f3e5','#304232','#6b7d33'],'layout':'friendly','feature':'species','sectionTitle':'Cada compañero es diferente.','cta':'Preparar consulta','services':['Consulta general','Consulta felina','Prevención','Primera visita'],'story':'Conocer a tu compañero también es conocerte a ti. La propuesta facilita explorar servicios por especie y preparar una consulta. No incluye diagnóstico ni atención urgente.','storyImage':'vet'})
site('taller-torque','TORQUE Garage','Taller mecánico','garage','garage','TU COCHE.<br>SIN RODEOS.','Información clara, servicios concretos y una primera consulta bien preparada. Mantenimiento con transparencia desde el primer clic.','PRECISIÓN / OFICIO / CONFIANZA',[
['Cambio de aceite','Mantenimiento',89,'Desde 89 € de ejemplo · Depende de aceite, filtro y modelo.'],['Revisión general','Mantenimiento',65,'Desde 65 € de ejemplo · Alcance sujeto a valoración.'],['Diagnóstico electrónico','Diagnóstico',45,'Desde 45 € de ejemplo · Consulta las condiciones.'],['Frenos','Seguridad',0,'Revisión y presupuesto tras inspección.'],['Neumáticos','Seguridad',0,'Consulta medidas, disponibilidad y montaje.']],{'colors':['#101b28','#e9f0f8','#4aa5ff'],'layout':'technical','feature':'garage','sectionTitle':'Prepara tu visita al taller.','cta':'Solicitar valoración','services':['Cambio de aceite','Revisión general','Diagnóstico electrónico','Frenos','Neumáticos'],'story':'Un servicio se entiende mejor cuando sabes qué se revisa. Explora el catálogo, selecciona tu vehículo y genera un resumen para una valoración posterior.','storyImage':'garage'})
site('academia-level','LEVEL Academy','Academia de idiomas','academy','academy','Abre una<br>nueva conversación.','Idiomas para usarlos. Grupos por nivel, objetivos claros y un programa que puedas encajar en tu semana.','APRENDE / PRACTICA / CONECTA',[
['English Starter','A1–A2',69,'Lunes y miércoles · 18:00 · Precio mensual de ejemplo'],['English Conversation','B1–B2',79,'Martes y jueves · 19:00 · Precio mensual de ejemplo'],['Business English','B1–B2',95,'Viernes · 18:00 · Precio mensual de ejemplo'],['Advanced Lab','C1',89,'Martes y jueves · 20:00 · Precio mensual de ejemplo'],['Español cotidiano','A1–A2',69,'Lunes y miércoles · 10:00 · Precio mensual de ejemplo']],{'colors':['#f6f2ff','#30235c','#7354ce'],'layout':'playful','feature':'courses','sectionTitle':'Encuentra tu próximo nivel.','cta':'Preparar inscripción','services':['Prueba de nivel','English Starter','English Conversation','Business English','Advanced Lab','Español cotidiano'],'story':'Hablar más y memorizar menos: una propuesta que presenta niveles, modalidades y horarios antes de preparar una inscripción. El resultado de la prueba orientativa no certifica un nivel.','storyImage':'academy'})
import sys
if '--from-json' in sys.argv:
 sites=json.loads((R/'sites.json').read_text())
(R/'sites.json').write_text(json.dumps(sites,ensure_ascii=False,indent=2))

def bi(es,en='',tag='span',cls=''):
 return f'<{tag} class="{cls}" data-es="{E(es,quote=True)}" data-en="{E(en or es,quote=True)}">{es}</{tag}>'
def image(name,alt,cls='',lazy=True):return f'<img class="{cls}" src="../assets/{name}.webp" alt="{E(alt)}" width="1400" height="1000" '+('loading="lazy" 'if lazy else 'fetchpriority="high" ')+ 'decoding="async">'
def intro(kicker,title,lead=''):
 return f'<div class="section-head"><div><p class="eyebrow">{kicker}</p><h2>{title}</h2></div>'+ (f'<p>{lead}</p>'if lead else '')+'</div>'
def faq(items):
 return '<section class="section faq" id="preguntas">'+intro('UN POCO MÁS DE INFORMACIÓN','Resolvemos lo importante.')+'<div class="faq-grid">'+''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>'for q,a in items)+'</div></section>'
def form_block(d,guest=False):
 opts=d.get('serviceOptions',d.get('services',[]));label='Preparar solicitud'if guest else d['cta'];title='¿Te ayudamos con algo?'if guest else 'El siguiente paso empieza aquí.'
 return f'''<section class="section contact-section" id="contacto"><div><p class="eyebrow">{'TU CONCIERGE DIGITAL'if guest else 'HABLEMOS'}</p><h2>{title}</h2><p>{'Prepara una petición para el equipo del alojamiento.'if guest else 'Cuéntanos qué necesitas y prepara tu consulta con todos los detalles.'}</p><div class="contact-note"><span class="status-dot"></span><p>Modo demostración. Puedes probar el flujo sin enviar información a ningún negocio.</p></div><p class="fine">Campos con * obligatorios. La solicitud se genera en tu navegador; no equivale a una reserva confirmada.</p></div><form class="request-form" data-brand="{E(d['name'])}"><div class="form-row"><label>Nombre *<input name="name" autocomplete="name" required maxlength="80" placeholder="Tu nombre"></label><label>{'Habitación / apartamento'if guest else 'Correo electrónico *'}<input name="{'room'if guest else 'email'}" {'type="email" required autocomplete="email"'if not guest else 'maxlength="40"'} placeholder="{'Ejemplo: 204'if guest else 'nombre@ejemplo.com'}"></label></div><label>{'¿Qué necesitas?'if guest else 'Servicio'}<select name="service">{''.join(f'<option>{E(o)}</option>'for o in opts)}</select></label><div class="form-row"><label>Fecha preferida *<input name="date" type="date" required></label><label>Hora preferida<select name="time"><option>09:00</option><option>11:00</option><option>13:00</option><option>16:00</option><option>18:00</option><option>20:00</option></select></label></div><label>Detalles<textarea name="message" rows="3" maxlength="2000" placeholder="Añade preferencias o información útil para tu solicitud."></textarea></label><label class="check"><input type="checkbox" name="consent" required><span>Entiendo que es una demo y que no se enviará una reserva real.</span></label><button class="btn" type="submit">{label} <span aria-hidden="true">↗</span></button><div class="request-result" hidden><h3>Solicitud preparada.</h3><p>No enviada. Revisa los detalles:</p><textarea readonly aria-label="Resumen de la solicitud" rows="6"></textarea><div class="button-row"><button type="button" class="btn outline" data-copy-result>Copiar</button><button type="button" class="btn outline" data-download-result>Descargar</button><button type="button" class="btn outline" data-calendar>Guardar recordatorio</button></div><p class="form-status" role="status"></p></div></form></section>'''
def shell(d,content):
 g=d.get('guest',False);c=d['colors'];nav=[('guia','Tu estancia'),('experiencias','Descubre'),('contacto','Ayuda')]if g else [('coleccion',{'menu':'La carta','classes':'Clases','properties':'Viviendas','courses':'Cursos'}.get(d.get('feature'),'Servicios')),('historia','El espacio'),('contacto','Contacto')]
 header=f'''<a class="skip-link" href="#main">Saltar al contenido</a><div class="demo-bar"><a href="../index.html">← Nexora / Demo Lab</a><span>Concepto ficticio · {'GuestHub'if g else 'Web comercial'}</span><button type="button" data-info>Sobre esta demo</button></div><header class="site-header"><a href="#inicio" class="brand">{d['name']}<span class="brand-dot"></span></a><button class="menu-button" aria-expanded="false" aria-controls="site-nav">Menú <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="Principal">{''.join(f'<a href="#{i}">{n}</a>'for i,n in nav)}</nav><div class="header-actions">{('<button class="lang-button" type="button" aria-label="Cambiar idioma de la guía" data-lang>EN</button>'if g else '')}<a class="btn small" href="#contacto">{'Pedir ayuda'if g else d['cta']} ↗</a></div></header>'''
 footer=f'''<footer><div class="footer-word">{d['name']}</div><div class="footer-links"><span>{d['kind']} · Concepto Nexora</span><a href="../index.html">Ver las 15 demos ↗</a><button data-info type="button">Información de la demo</button><button type="button" data-reset>Restablecer preferencias</button></div><p class="fine">Marca, servicios, horarios y precios ilustrativos. No se realizan pagos, reservas ni envíos reales.</p></footer><button class="to-top" type="button" aria-label="Volver al inicio" hidden>↑</button><div class="toast" role="status" aria-live="polite"></div><dialog class="detail-dialog" aria-labelledby="dialog-title"><button class="dialog-close" type="button" aria-label="Cerrar detalle">×</button><div class="dialog-body"></div></dialog>'''
 return f'''<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(d['name'])} · {E(d['kind'])} | Nexora Demo</title><meta name="description" content="{E(d['lead'])}"><meta name="theme-color" content="{c[0]}"><link rel="icon" href="../assets/mark.svg"><link rel="stylesheet" href="../assets/fonts.css"><link rel="stylesheet" href="../assets/site.css?v=2"><link rel="stylesheet" href="theme.css"><script src="data.js" defer></script><script src="../assets/site.js" defer></script></head><body class="theme-{d['theme']} layout-{d['layout']} {'guest-site'if g else 'business-site'}" data-site="{d['slug']}" style="--bg:{c[0]};--ink:{c[1]};--accent:{c[2]}">{header}<main id="main" tabindex="-1">{content}</main>{footer}</body></html>'''
def hero(d):
 g=d.get('guest');title=bi(d['title'],d.get('enTitle'),'h1')if g else f'<h1>{d["title"]}</h1>';lead=bi(d['lead'],d.get('enLead'),'p','hero-lead')if g else f'<p class="hero-lead">{d["lead"]}</p>'
 text=f'<div class="hero-text"><p class="eyebrow">{d["tag"]}</p>{title}{lead}<div class="button-row"><a class="btn" href="#{"guia"if g else "coleccion"}">{"Explorar mi estancia"if g else "Descubrir"} ↗</a><a class="text-link" href="#contacto">{"Pedir ayuda"if g else d["cta"]} →</a></div></div>'
 visual=f'<div class="hero-image">{image(d["image"],d["kind"],lazy=False)}<span class="image-label">{d.get("place",d["name"])} / CONCEPTO NEXORA</span></div>'
 stamp='<div class="hero-stamp"><span>HECHO PARA</span><strong>vivirlo.</strong><span>NO SOLO PARA VERLO</span></div>'
 if d['layout']=='dashboard':
  return f'<section class="hero dashboard-hero" id="inicio"><div>{text}<div class="guest-summary"><span class="status-dot"></span><div><strong>Tu estancia, en un vistazo.</strong><p>Check-in 16:00 / Check-out 11:00</p></div></div></div>{visual}</section>'
 if d['layout']=='poster':return f'<section class="hero poster-hero" id="inicio">{text}{visual}<div class="poster-label">GOOD PEOPLE.<br>GREAT STORIES.</div></section>'
 if d['layout']=='bento':return f'<section class="hero bento-hero" id="inicio">{text}<div class="hero-bento">{visual}<div class="bento-note"><span>01 / ESCUCHAR</span><strong>Antes de tratar,<br>entender.</strong></div><div class="bento-note accent"><span>02 / EXPLICAR</span><strong>Cada paso,<br>con claridad.</strong></div></div></section>'
 if d['layout']=='property':return f'<section class="hero property-hero" id="inicio">{text}{visual}<div class="property-tag">ESPACIOS CON ALGO QUE CONTAR ↗</div></section>'
 if d['layout']=='editorial':return f'<section class="hero editorial-hero" id="inicio">{text}{visual}<div class="editorial-number">01 / {"LA ESTANCIA"if g else "EL ESPACIO"}</div></section>'
 if d['layout']=='arch':return f'<section class="hero arch-hero" id="inicio">{text}{visual}{stamp}</section>'
 if d['layout']=='centered':return f'<section class="hero centered-hero" id="inicio">{visual}{text}<a href="#coleccion" class="hero-scroll">SCROLL PARA SABOREAR ↓</a></section>'
 if d['layout']=='kinetic':return f'<section class="hero kinetic-hero" id="inicio">{visual}{text}<span class="kinetic-label">TRAIN TO FEEL.</span></section>'
 if d['layout']=='magazine':return f'<section class="hero magazine-hero" id="inicio">{text}{visual}<span class="edition">EST. CONCEPTO / VOL. 01</span></section>'
 return f'<section class="hero" id="inicio">{text}{visual}{stamp}</section>'

enguides=[
[['A smooth arrival','From 15:00','Reception is open 08:00–23:00. Prepare a request if you plan to arrive later.'],['Breakfast by the sea','07:30–10:30','Breakfast on the ground-floor terrace. Ask about plant-based options.'],['Pool & sun deck','09:00–20:00','Towels by the entrance. Children must be accompanied.'],['Your last morning','Check-out by 11:00','Return your key at reception. Ask about luggage storage.']],
[['Your apartment access','From 16:00','Real access codes would be shared privately. This demo contains no real codes.'],['Coffee & cowork','08:00–19:00','Find a seat in the lounge to work or plan your day.'],['Around the city','Discover the neighbourhood','Ask your host for transport recommendations before heading out.'],['A simple check-out','By 11:00','Check your belongings, close the windows and follow the key-return guide.']],
[['A warm welcome','From 15:00','Your host welcomes you in the courtyard. Prepare a request for arrival outside regular hours.'],['The house kitchen','Share the table','Find labelled utensils and separate waste in the courtyard bins.'],['Fireplace & rest','Enjoy responsibly','Ask your host before lighting the fireplace and follow house instructions.'],['Trails near the house','Choose your pace','Check route difficulty, weather and equipment with your host before leaving.']],
[['A personal welcome','From 15:00','Find our team in the entrance lounge. Share any needs before arrival.'],['Breakfast at your pace','08:00–11:00','Prepare your preference in the request form. Reception will confirm availability.'],['Spa & wellbeing','On request','Ask about treatments and opening hours.'],['Library & lounge','Your favourite pause','Read, enjoy a coffee or explore our design selection.']],
[['Your first stop','From 15:00','Collect your key at the desk and ask about the week’s activities.'],['Shared kitchen','07:00–23:00','Label your food and clean up after use. Sharing means caring.'],['Chill area','Meet, then rest','Games and conversation until 23:00. Quiet time afterwards.'],['Your backpack','Ask the desk','Request information about lockers. Never share personal access codes.']]]
expEN=[['Coastal walk','Local producers market','Sunset kayaking'],['Architecture walk','Specialty coffee','Neighbourhood stroll'],['Forest trail','Bread-making workshop','Seasonal picnic'],['Architecture & design','Seasonal tasting','Private cultural walk'],['Group walking tour','Shared dinner','Street art trail']]
def guest_content(d,n):
 guide=''.join(f'''<article class="guide-card reveal"><span class="card-icon">{['↗','◷','✳','⌂'][i]}</span><p class="eyebrow">{E(item[3])}</p>{bi(item[0],enguides[n][i][0],'h3')}{bi(item[1],enguides[n][i][1],'p','meta')}{bi(item[2],enguides[n][i][2],'p')}<button type="button" class="text-link" data-guide="{i}">{bi('Ver detalle','See details')} ↗</button></article>'''for i,item in enumerate(d['items']))
 quick=f'''<section class="quick-actions" aria-label="Accesos rápidos"><button type="button" data-wifi><span>⌁</span>{bi('Wi-Fi','Wi-Fi')}<small>{bi('Conectar y copiar','Connect & copy')}</small></button><a href="#guia"><span>↗</span>{bi('Llegada','Arrival')}<small>{bi('Tu primer paso','Your first step')}</small></a><a href="#experiencias"><span>✳</span>{bi('Descubrir','Explore')}<small>{bi('Planes cerca de ti','Ideas nearby')}</small></a><a href="#contacto"><span>◌</span>{bi('Ayuda','Help')}<small>{bi('Prepara una solicitud','Prepare a request')}</small></a></section>'''
 experiences=''.join(f'''<article class="experience-card reveal">{image(['sea','workspace','mountains','room','city'][n],x)}<div><span class="experience-number">0{i+1}</span>{bi(x,expEN[n][i],'h3')}<p>{bi('Una idea para descubrir el entorno. Consulta horarios, disponibilidad y condiciones con el alojamiento.','An idea to explore your surroundings. Ask the property about opening hours, availability and conditions.')}</p><div class="button-row"><button class="text-link" data-experience="{i}" type="button">{bi('Ver plan','Explore idea')} ↗</button><button class="save-button" data-save="experience-{i}" type="button" aria-pressed="false">{bi('Guardar','Save')} ♡</button></div></div></article>'''for i,x in enumerate(d['experience']))
 checklist=f'''<section class="section stay-checklist" id="llegada"><div>{bi('TU PRIMER DÍA','YOUR FIRST DAY','p','eyebrow')}{bi('Una llegada<br>sin preguntas.','A smooth<br>arrival.','h2')}{bi('Marca los pasos que ya tienes preparados. Tu progreso se guarda solo en este dispositivo.','Tick the steps you have prepared. Your progress stays on this device.','p')}<div class="check-progress"><span data-progress>0 / 4</span><progress max="4" value="0" aria-label="Pasos de llegada completados"></progress></div></div><div class="checklist">{''.join(f'<label><input type="checkbox" data-check="{i}">{bi(es,en)}<span aria-hidden="true">0{i+1}</span></label>'for i,(es,en)in enumerate([('He revisado el horario de llegada','I have checked arrival times'),('Tengo localizada la recepción','I know where to check in'),('He leído la guía del alojamiento','I have read the property guide'),('He preparado mis preferencias','I have prepared my preferences')]))}</div></section>'''
 essentials=f'''<section class="section essentials"><div class="essentials-title">{bi('PEQUEÑOS DETALLES','SMALL DETAILS','p','eyebrow')}{bi('Lo esencial,<br>a mano.','The essentials,<br>at hand.','h2')}</div><div>{bi('Convivencia','Living together','h3')}{bi('Respeta las zonas de descanso. Los servicios, horarios y normas de esta demo son ilustrativos.','Please respect quiet areas. Services, hours and rules in this demo are illustrative.','p')}</div><div>{bi('Tu salida','Your departure','h3')}{bi('Revisa tus pertenencias y prepara cualquier petición antes del último día.','Check your belongings and prepare requests before your last day.','p')}</div><div>{bi('Cuando necesitas ayuda','When you need help','h3')}{bi('Para consultas, utiliza el formulario de demostración. Ante una emergencia real, llama al 112.','For enquiries, use the demo request form. In a real emergency, call 112.','p')}<a href="tel:112" class="text-link">112 · Emergencias</a></div></section>'''
 fa=faq([('¿Esta guía corresponde a un alojamiento real?','No. Es una marca ficticia creada por Nexora para mostrar el concepto de GuestHub.'),('¿Mi solicitud llega a recepción?','No en esta demo. Puedes copiarla, descargarla o guardar un recordatorio. Una versión real se conectaría al canal autorizado del alojamiento.'),('¿Qué se guarda en mi dispositivo?','Solo el idioma, los favoritos y tu lista de llegada. La solicitud no se guarda de forma permanente.')])
 return hero(d)+quick+f'<section class="section" id="guia"><div class="section-head"><div>{bi("TU ESTANCIA, A TU RITMO","YOUR STAY, YOUR WAY","p","eyebrow")}{bi("Todo en su sitio.","Everything in its place.","h2")}</div>{bi("Una guía que acompaña cada momento. Sin papeles, sin buscar entre mensajes.","A guide for every moment. No paperwork, no searching through messages.","p")}</div><div class="guide-grid">{guide}</div></section>'+checklist+f'<section class="section" id="experiencias"><div class="section-head"><div>{bi("FUERA DE TU HABITACIÓN","BEYOND YOUR ROOM","p","eyebrow")}{bi("Sal. Descubre. Disfruta.","Go out. Explore. Enjoy.","h2")}</div><p>{bi("Guarda ideas para más tarde.","Save ideas for later.")}</p></div><div class="experience-grid">{experiences}</div></section>'+essentials+form_block(d,True)+fa

def business_content(d):
 f=d['feature'];items=d['items'];cats=list(dict.fromkeys(i[1]for i in items));filters=''.join(f'<button type="button" data-filter="{E(c)}" aria-pressed="false">{c}</button>'for c in cats)
 def cards():
  output=[]
  for i,it in enumerate(items):
   name,cat,price,desc=it;pic=d['image']
   if f=='properties':pic=['interior','home','room','workspace'][i]
   photo=image(pic,name)if f in ['properties','courses']else ''
   pricehtml=f'<span class="item-price">{price:,.0f} €'+('/mes'if cat=='Alquiler'or f=='courses'else '')+'</span>'if price else '<span class="item-price">Consultar</span>'
   action=f'<button type="button" class="text-link" data-item="{i}">{"Ver vivienda"if f=="properties"else "Ver detalles"} ↗</button>'
   save=f'<button class="save-button" type="button" data-save="item-{i}" aria-pressed="false">Guardar ♡</button>'if f=='properties'else ''
   output.append(f'<article class="catalog-card reveal" data-category="{E(cat)}" data-search="{E(name+" "+desc)}">{photo}<div class="catalog-inner"><p class="eyebrow">{cat}</p><h3>{name}</h3><p>{desc}</p><div class="item-bottom">{pricehtml}{action}{save}</div></div></article>')
  return ''.join(output)
 widget=''
 if f=='estimate':
  widget='''<div class="estimate-tool"><div><label>Superficie aproximada <output id="area-output">60 m²</output><input id="area" type="range" min="10" max="200" value="60" step="5"></label><label>Tipo de intervención<select id="finish"><option value="450">Actualización</option><option value="750" selected>Reforma integral</option><option value="1100">Reforma con acabados premium</option></select></label><label class="check"><input id="kitchen" type="checkbox"><span>Incluir partida de cocina de ejemplo (+8.000 €)</span></label></div><div class="estimate-value"><span>SIMULACIÓN ORIENTATIVA</span><strong id="estimate-total">45.000 €</strong><p>Ejemplo comercial, no presupuesto. No incluye impuestos, licencias ni valoración técnica.</p><button type="button" class="btn" data-use-estimate>Preparar consulta con esta idea ↗</button></div></div>'''
 if f=='garage':widget='''<div class="garage-tool"><label>Tipo de vehículo<select id="vehicle"><option>Turismo</option><option>SUV / crossover</option><option>Furgoneta</option></select></label><label>Consulta principal<select id="garage-service"><option>Cambio de aceite</option><option>Revisión general</option><option>Diagnóstico electrónico</option><option>Frenos</option><option>Neumáticos</option></select></label><button class="btn" data-use-garage type="button">Llevar selección a mi consulta ↗</button></div>'''
 if f=='courses':widget='''<div class="course-search"><label>Busca tu curso<input type="search" id="course-search" placeholder="Conversación, business, español…"></label><button type="button" class="btn outline" data-level>Prueba orientativa de nivel ↗</button></div>'''
 if f=='properties':widget='''<div class="property-filters"><label>Precio máximo <select id="max-price"><option value="999999">Sin límite</option><option value="1500">1.500 €</option><option value="450000">450.000 €</option><option value="600000">600.000 €</option></select></label><label class="check"><input type="checkbox" id="only-saved"><span>Solo favoritos</span></label></div>'''
 filterbar=f'<div class="filter-bar" role="group" aria-label="Filtrar {d["kind"]}"><button type="button" data-filter="all" aria-pressed="true">Todos</button>{filters}</div>'if f!='estimate'else ''
 collection=f'<section class="section collection-section" id="coleccion">{intro("EXPLORA / ELIGE / DESCUBRE",d["sectionTitle"],"Información y precios ilustrativos para esta propuesta de diseño.")}{widget}{filterbar}<p class="empty-state" hidden>No hay resultados con esos filtros. Prueba otra selección.</p><div class="catalog-grid">{cards()}</div></section>'
 marquee=f'<div class="marquee" aria-hidden="true"><div>{(" · "+d["tag"])*6}</div></div>'
 story=f'<section class="section story" id="historia"><div class="story-image">{image(d["storyImage"],"Concepto de espacio para "+d["name"])}</div><div><p class="eyebrow">UNA EXPERIENCIA CON IDENTIDAD</p><h2>{ {"restaurant":"La mesa como punto de encuentro.","dental":"Primero, escuchar.","barber":"Oficio en cada detalle.","gym":"Tu club. Tu ritmo.","interior":"El diseño se vive.","home":"Cada casa, una historia.","beauty":"El cuidado está en los detalles.","vet":"Un equipo que acompaña.","garage":"La confianza se explica.","academy":"Aprender para conectar."}[d["theme"]] }</h2><p>{d["story"]}</p><a href="#contacto" class="text-link">Hablemos de lo que necesitas ↗</a><div class="story-points"><span>01 / EXPLORAR</span><span>02 / PREPARAR</span><span>03 / CONECTAR</span></div></div></section>'
 extra=''
 if f=='classes':extra='''<section class="section plans"><div class="section-head"><div><p class="eyebrow">TU FORMA DE ENTRENAR</p><h2>Elige tu plan.</h2></div><div class="billing" role="group" aria-label="Facturación"><button data-billing="month" aria-pressed="true">Mensual</button><button data-billing="year" aria-pressed="false">Anual · −15%</button></div></div><div class="plan-grid">'''+''.join(f'<article><p>{name}</p><h3><span data-plan-price="{p}">{p}</span> €<small>/mes equivalente</small></h3><p>{desc}</p><button type="button" data-plan="{name}" class="btn">Preparar interés ↗</button></article>'for name,p,desc in [('CORE',39,'Sala de entrenamiento y programación general.'),('PLUS',59,'Sala, clases de grupo y sesiones de seguimiento.'),('COACH',99,'Un enfoque personal con sesiones de ejemplo.')])+'''</div><p class="fine">Tarifas de ejemplo. El modo anual muestra el equivalente mensual con un 15% de descuento; no se realizan cobros.</p></section>'''
 if f=='services'and d['theme']=='barber':extra='<section class="section team">'+intro('TRES ESTILOS / UN MISMO OFICIO','Tu silla, tu profesional.')+'<div class="team-grid">'+''.join(f'<article><span class="team-monogram">{x[0]}</span><h3>{x.split(" · ")[0]}</h3><p>{x.split(" · ")[1]}</p><button class="text-link" type="button" data-team="{x.split(" · ")[0]}">Elegir preferencia ↗</button></article>'for x in d['team'])+'</div><p class="fine">Equipo ficticio para mostrar el flujo de selección.</p></section>'
 if f=='courses':extra='<section class="section learning-path">'+intro('UN PROCESO QUE TIENE SENTIDO','Un paso cada vez.')+'<div class="process-grid">'+''.join(f'<article><span>0{i+1}</span><h3>{x}</h3><p>{y}</p></article>'for i,(x,y)in enumerate([('Encuentra tu punto de partida','La prueba orientativa ayuda a plantear una primera conversación.'),('Elige tu programa','Compara objetivos, nivel y horarios de ejemplo.'),('Practica con intención','Plantea tus preferencias para una inscripción posterior.')]))+'</div></section>'
 if f not in ['classes','courses']:
  extra+='<section class="section process">'+intro('UN CAMINO SENCILLO','Del primer clic al siguiente paso.')+'<div class="process-grid">'+''.join(f'<article><span>0{i+1}</span><h3>{x}</h3><p>{y}</p></article>'for i,(x,y)in enumerate([('Explora con calma','Encuentra el servicio o propuesta que encaja contigo.'),('Prepara los detalles','Selecciona una preferencia y genera un resumen claro.'),('Decide cómo seguir','En esta demo, copia o descarga tu solicitud sin enviarla.')]))+'</div></section>'
 fa=faq([('¿Es un negocio real?','No. Esta marca y sus datos son ficticios. Nexora ha creado la propuesta para enseñar diseño, navegación y funciones comerciales.'),('¿Los precios y horarios son definitivos?','Son datos de ejemplo. Una implantación real requiere que el negocio valide precios, disponibilidad y condiciones.'),('¿Puedo hacer una reserva o pago real?','No. Las solicitudes se preparan localmente y se pueden descargar. No se reservan plazas ni se cobra ningún importe.')])
 return hero(d)+marquee+collection+story+extra+form_block(d)+fa

for i,d in enumerate(sites):
 p=R/d['slug'];p.mkdir(exist_ok=True)
 content=guest_content(d,i)if d.get('guest')else business_content(d)
 (p/'index.html').write_text(shell(d,content));(p/'data.js').write_text('window.DEMO='+json.dumps(d,ensure_ascii=False)+';')
 (p/'theme.css').write_text('/* Identity: '+d['name']+' */\n'+{'coast':'.hero h1{font-family:"Cormorant Garamond",Georgia,serif;font-weight:500;font-size:clamp(64px,7.8vw,118px)}.hero-image{border-radius:180px 180px 20px 20px}.guide-grid{grid-template-columns:repeat(4,1fr)}.guide-card{border-radius:24px}.quick-actions{border-radius:80px;background:#fff9}.experience-card img{border-radius:140px 140px 12px 12px}.essentials{background:#dee8df}',
 'city':'.site-header{border-bottom:1px solid #ffffff20}.hero-image{border-radius:26px}.dashboard-hero{background:radial-gradient(circle at 10% 90%,#75e1e617,transparent 65%)}.guide-card{background:#1a2332}.quick-actions{background:#1a2332}.experience-card{background:#1a2332}.essentials{background:#192537}.request-form{background:#1a2332}.guest-summary{display:flex;gap:16px;align-items:center;border-top:1px solid #ffffff25;margin-top:35px;padding-top:25px}.hero h1{letter-spacing:-6px}.guide-grid{grid-template-columns:repeat(2,1fr)}',
 'forest':'.hero h1,h2{font-family:"Cormorant Garamond",Georgia,serif;font-weight:500}.hero-image{border-radius:220px 220px 0 0}.guide-card{border:0;border-top:1px solid #73846c;border-radius:0;background:transparent}.quick-actions{background:#e0e4d3;border:0}.experience-card{border-radius:0}.essentials{background:#293e2b;color:#f0f1e1}.request-form{border-radius:4px}.checklist label{border-radius:0}.footer-word{font-family:Georgia,serif}',
 'boutique':'.hero h1,h2{font-family:"Cormorant Garamond",Georgia,serif;font-weight:500}.hero-image{border-radius:50% 50% 10px 10px}.hero-stamp{border-radius:50%;border:1px solid var(--accent);background:var(--bg);color:var(--ink);width:170px;height:170px;transform:rotate(-12deg)}.guide-card{text-align:center;border-radius:180px 180px 15px 15px;padding-top:45px}.experience-card img{border-radius:100px 100px 0 0}.quick-actions{border-radius:0;border-top:1px solid var(--accent);border-bottom:1px solid var(--accent)}.essentials{background:#e9dfe8}',
 'hostel':'.hero h1{font-family:Arial,sans-serif;font-weight:900;letter-spacing:-7px}.hero-image{border-radius:0;transform:rotate(3deg);border:8px solid var(--ink)}.poster-label{background:var(--accent);padding:25px;font-weight:900;transform:rotate(-6deg);position:absolute;right:6%;bottom:18px;font-size:23px;z-index:2}.guide-card,.experience-card,.request-form{border-radius:0;border:2px solid var(--ink)}.quick-actions{background:var(--accent);border:2px solid var(--ink)}.btn{border-radius:0;border:2px solid var(--ink);box-shadow:4px 4px 0 var(--ink)}.essentials{background:var(--ink);color:var(--bg)}.footer-word{font-weight:900;text-transform:uppercase}',
 'restaurant':'.hero{color:#f4ead9}.hero h1,h2{font-family:"Cormorant Garamond",Georgia,serif;font-weight:600}.hero h1{font-size:clamp(70px,8vw,120px)}.catalog-card{border:0;border-bottom:1px solid #f3e9d82b;background:transparent;border-radius:0}.catalog-grid{grid-template-columns:repeat(2,1fr)}.story-image{border-radius:160px 160px 10px 10px}.item-price{font-family:Georgia,serif;font-size:30px}.request-form{background:#27271f}.btn{border-radius:3px}.marquee{border-top:1px solid #f1e7d130;border-bottom:1px solid #f1e7d130}.footer-word{font-family:Georgia,serif}',
 'dental':'.hero h1{letter-spacing:-5px}.bento-note{background:#cde9ed}.bento-note.accent{background:var(--ink);color:#fff}.catalog-card{border-radius:30px;background:#fff}.catalog-card:nth-child(2){background:#d6ecf0}.story-image{border-radius:30px}.process-grid article{border-radius:22px;background:#dceef1;padding:30px}.brand{font-weight:600}.btn{border-radius:50px}',
 'barber':'.hero h1{font-weight:900;font-family:Arial,sans-serif;letter-spacing:-6px}.hero-image{border-radius:0}.catalog-card{border-radius:0;border:1px solid var(--ink);background:transparent}.catalog-grid{grid-template-columns:repeat(3,1fr)}.btn{border-radius:0}.team-grid article{border:1px solid var(--ink);padding:30px}.team-monogram{font-family:Georgia,serif;font-size:90px}.story-image{filter:grayscale(1)}.footer-word{font-weight:900;text-transform:uppercase}.marquee{background:var(--ink);color:var(--bg)}',
 'gym':'.hero h1{font-family:Arial,sans-serif;font-style:italic;font-weight:900;letter-spacing:-7px}.hero-image{border-radius:0}.catalog-card{border-radius:0;border:1px solid #e6f3d135;background:#192019}.btn{border-radius:0;text-transform:uppercase;font-weight:800}.plans{background:var(--accent);color:#111}.plans .btn{background:#111;color:var(--accent)}.plan-grid article{border:2px solid #111;border-radius:0}.marquee{background:var(--accent);color:#111;font-style:italic}.request-form{background:#192019}.footer-word{font-style:italic;font-weight:900}',
 'interior':'.hero h1,h2{font-family:"Cormorant Garamond",Georgia,serif;font-weight:500}.hero-image{border-radius:0}.catalog-card{border-radius:0;background:transparent;border:0;border-top:1px solid #806a5860}.catalog-grid{grid-template-columns:repeat(2,1fr)}.estimate-tool{background:#e7ddd0}.btn{border-radius:0}.story-image{border-radius:0}.editorial-number{font-family:monospace}.footer-word{font-family:Georgia,serif}',
 'home':'.hero h1{font-weight:500;letter-spacing:-5px}.property-tag{background:var(--ink);color:white;padding:18px 28px;position:absolute;bottom:0;right:8%;font-size:12px;letter-spacing:2px}.hero-image{border-radius:0}.catalog-card{background:white;border-radius:22px;overflow:hidden}.catalog-card img{height:220px;border-radius:0}.catalog-grid{grid-template-columns:repeat(2,1fr)}.property-filters{background:#fff;border-radius:15px}.story-image{border-radius:200px 200px 10px 10px}.btn{border-radius:12px}',
 'beauty':'.hero h1,h2{font-family:"Cormorant Garamond",Georgia,serif;font-weight:500}.hero h1{font-size:clamp(74px,9vw,132px)}.hero-image{border-radius:260px 260px 15px 15px}.catalog-card{background:#f0e2e5;border:0;border-radius:80px 80px 16px 16px;padding-top:25px}.catalog-card:nth-child(2n){background:#e8dcdf}.story-image{border-radius:220px 220px 15px 15px}.btn{border-radius:40px}.process-grid{border-top:1px solid #b898a4}.footer-word{font-family:Georgia,serif}',
 'vet':'.hero h1{font-weight:500;letter-spacing:-4px}.hero-image{border-radius:60px 160px 60px 60px}.catalog-card{background:#fff;border-radius:26px}.catalog-card:nth-child(2n){background:#e3e8c9}.story-image{border-radius:60px}.btn{border-radius:40px}.process-grid article{background:#e6e7ce;padding:30px;border-radius:30px}.hero-stamp{border-radius:50%;background:var(--accent);color:white}.marquee{background:#dce2bc}',
 'garage':'.hero h1{font-family:Arial,sans-serif;font-weight:900;letter-spacing:-6px}.hero-image{border-radius:8px}.catalog-card{border-radius:6px;border:1px solid #8cc5ff30;background:#172a3c}.catalog-grid{grid-template-columns:repeat(3,1fr)}.garage-tool{background:#1c3248;border-radius:8px}.btn{border-radius:6px}.story-image{border-radius:6px}.process-grid article{border-top:2px solid var(--accent)}.request-form{background:#172a3c}.footer-word{font-family:monospace;font-weight:900}',
 'academy':'.hero h1{font-weight:500;letter-spacing:-5px}.hero-image{border-radius:60px 60px 180px 60px;transform:rotate(-3deg)}.hero-stamp{border-radius:30px;background:#ffda69;color:#30235c;transform:rotate(8deg)}.catalog-card{border-radius:24px;background:#fff;overflow:hidden}.catalog-card img{height:180px;filter:saturate(.6)}.catalog-grid{grid-template-columns:repeat(3,1fr)}.process-grid article{background:#e4dcf6;padding:30px;border-radius:22px}.btn{border-radius:16px}.marquee{background:#ffda69}.course-search{background:#e5def5;border-radius:22px}.footer-word{font-weight:500}'}[d['theme']])
print('Built',len(sites),'distinct demo sites')
